# syntax=docker/dockerfile:1.19.0
# This file is generated by Dofigen v2.7.0
# See https://github.com/lenra-io/dofigen

# minify
FROM node@sha256:5209bcaca9836eb3448b650396213dbe9d9a34d31840c2ae1f206cb2986a8543 AS minify
LABEL \
    org.opencontainers.image.base.digest="sha256:5209bcaca9836eb3448b650396213dbe9d9a34d31840c2ae1f206cb2986a8543" \
    org.opencontainers.image.base.name="docker.io/node:alpine"
WORKDIR /app
COPY \
    --link \
    "src/" "/app/src/"
RUN <<EOF
npm install -g esbuild html-minifier-terser
mkdir -p dist/js dist/css
esbuild src/js/app.js --bundle --minify --outfile=dist/js/app.js
esbuild src/css/styles.css --minify --outfile=dist/css/styles.css
html-minifier-terser --collapse-whitespace --remove-comments --remove-redundant-attributes --minify-css true --minify-js true -o dist/index.html src/index.html
EOF

# runtime
FROM nginxinc/nginx-unprivileged@sha256:ccbac1a4c20a8b41c5dd1691bd91d63eda3b7989d643a33fd47841838519bfb9 AS runtime
LABEL \
    io.dofigen.version="2.7.0" \
    org.opencontainers.image.base.digest="sha256:ccbac1a4c20a8b41c5dd1691bd91d63eda3b7989d643a33fd47841838519bfb9" \
    org.opencontainers.image.base.name="docker.io/nginxinc/nginx-unprivileged:alpine"
COPY \
    --from=minify \
    --chown=1000:1000 \
    --link \
    "/app/dist/" "/usr/share/nginx/html/"
USER 1000:1000
EXPOSE 8080
